# Generated by Django 4.2.7 on 2025-07-21 13:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.DecimalField(decimal_places=2, help_text='Campaign budget in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('target_volunteers', models.PositiveIntegerField(default=0, help_text='Target number of volunteers needed')),
                ('target_donations', models.DecimalField(decimal_places=2, default=0, help_text='Target donation amount in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('location', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=17)),
                ('website_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the campaign', null=True, upload_to='campaigns/images/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'campaign'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('update_type', models.CharField(choices=[('progress', 'Progress Update'), ('news', 'News'), ('milestone', 'Milestone'), ('announcement', 'Announcement'), ('alert', 'Alert')], default='progress', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('notify_volunteers', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=False)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='campaigns/updates/')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_updates', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='campaign_dashboard.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Update',
                'verbose_name_plural': 'Campaign Updates',
                'ordering': ['campaign', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('progress_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_campaign_tasks', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='campaign_dashboard.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Task',
                'verbose_name_plural': 'Campaign Tasks',
                'ordering': ['campaign', 'due_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='CampaignGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('volunteers', 'Volunteers'), ('donations', 'Donations'), ('events', 'Events'), ('outreach', 'Outreach'), ('custom', 'Custom')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='count', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='campaign_dashboard.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Goal',
                'verbose_name_plural': 'Campaign Goals',
                'ordering': ['campaign', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('declined', 'Declined')], default='invited', max_length=20)),
                ('volunteer_role', models.CharField(choices=[('volunteer', 'Volunteer'), ('coordinator', 'Coordinator'), ('lead', 'Team Lead'), ('specialist', 'Specialist')], default='volunteer', max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('skills_required', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('hours_committed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hours_logged', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_volunteers', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_volunteers', to='campaign_dashboard.campaign')),
                ('volunteer', models.ForeignKey(limit_choices_to={'role': 'volunteer'}, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Volunteer',
                'verbose_name_plural': 'Campaign Volunteers',
                'ordering': ['campaign', 'volunteer_role', '-assigned_date'],
                'unique_together': {('campaign', 'volunteer')},
            },
        ),
        migrations.CreateModel(
            name='CampaignMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('volunteers_registered', models.PositiveIntegerField(default=0)),
                ('volunteers_active', models.PositiveIntegerField(default=0)),
                ('volunteer_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('donations_count', models.PositiveIntegerField(default=0)),
                ('donations_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('events_held', models.PositiveIntegerField(default=0)),
                ('people_reached', models.PositiveIntegerField(default=0)),
                ('social_media_reach', models.PositiveIntegerField(default=0)),
                ('website_visits', models.PositiveIntegerField(default=0)),
                ('email_opens', models.PositiveIntegerField(default=0)),
                ('email_clicks', models.PositiveIntegerField(default=0)),
                ('social_shares', models.PositiveIntegerField(default=0)),
                ('social_likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='campaign_dashboard.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Metrics',
                'verbose_name_plural': 'Campaign Metrics',
                'ordering': ['campaign', '-date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
